### ISSUE TITLE
skip an at sign in a dn

### ISSUE THREAD

**Issue by lcami** [ForgeRock/opendj-community-edition#13]
Hi there, I am using openDJ 3.0.0-1 on CentOS7 and I would like to know if I can overcome the below error in my ldap search. I am trying to login into an application via the mail attribute. The search requested is the below:

base="login_user@domain.com" scope=sub filter="(objectClass=*)" attrs="ALL"

and the response is: 
The provided value "login_user@domain.com" could not be parsed as a valid distinguished name because character '@' at position 10 is not allowed in an attribute name"

Thanks

**Comment by chrisridd** [comment]
The value of "base" in an LDAP search must be a DN. "login_user@domain.com" is not a DN.
